name: grade_converted_flutter_app
description: Professional Grade Converter with Splash Screen
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  excel: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  fl_chart: ^0.66.2
  csv: ^5.0.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true