plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

group = 'com.example.studentgrades'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'org.apache.poi:poi:5.2.3'
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
    implementation 'org.apache.xmlbeans:xmlbeans:5.1.1'
    implementation 'com.fasterxml.woodstox:woodstox-core:6.5.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.18.0'
}

application {
    mainClass = 'com.example.studentgrades.MainConsoleKt'
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.example.studentgrades.MainConsoleKt"
    }
    configurations.runtimeClasspath.setCanBeResolved(true)
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
